title: Sugam Ghimire
email: sugmaghimire@gmail.com
description: >- 
  Student | Tech Enthusiast | Future Leader
baseurl: "" # leave empty for root
url: "https://sugamghimire.com.np"
twitter_username: sugamghimire
github_username:  sugamghimire

theme: minimal-mistakes-jekyll

minimal_mistakes_skin: "air"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: "Sugam Ghimire"
  avatar: "/assets/images/profile.jpg"
  bio: "Management Student | Interested in Tech, Business, and Creative Media"
  location: "Nepal"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:sugmaghimire@gmail.com"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://instagram.com/sugam_ghimire1"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/sugamghimire"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/yourprofile"

footer:
  links:
    - label: "GitHub"
      url: "https://github.com/sugamghimire"
    - label: "LinkedIn"
      url: "https://linkedin.com/in/yourprofile"

collections:
  portfolio:
    output: true
